// backend/services/blockchainService.js
import { ethers } from "ethers";
import dotenv     from "dotenv";
import fs         from "fs";
import path       from "path";

dotenv.config();

// ==============================
// Load Contract ABI
// Generated by Hardhat after
// npx hardhat compile
// ==============================

const abiPath = path.resolve(
  "../../contracts/artifacts/contracts/CopyrightVerifier.sol/CopyrightVerifier.json"
);

const contractJSON = JSON.parse(fs.readFileSync(abiPath, "utf8"));
const contractABI  = contractJSON.abi;

// ==============================
// Provider & Signer Setup
// Connects to Ethereum network
// ==============================

const provider = new ethers.JsonRpcProvider(
  process.env.ETHEREUM_RPC_URL     // e.g. https://sepolia.infura.io/v3/YOUR_KEY
);

const signer = new ethers.Wallet(
  process.env.PRIVATE_KEY,         // your wallet private key
  provider
);

// ==============================
// Contract Instance
// Connects to deployed contract
// ==============================

const contract = new ethers.Contract(
  process.env.CONTRACT_ADDRESS,    // deployed contract address
  contractABI,
  signer
);

// ==============================
// storeOnBlockchain()
// Stores verification result
// on Ethereum blockchain
// ==============================

export const storeOnBlockchain = async ({
  imageHash,
  score,
  certified,
  fileName,
}) => {
  try {

    console.log("[BLOCKCHAIN] Storing verification on chain...");

    // Step 1 — Call smart contract function
    const tx = await contract.storeVerification(
      imageHash,
      score,
      certified,
      fileName
    );

    console.log(`[BLOCKCHAIN] Transaction sent: ${tx.hash}`);

    // Step 2 — Wait for transaction to be mined
    const receipt = await tx.wait();

    console.log(`[BLOCKCHAIN] Mined in block: ${receipt.blockNumber}`);

    // Step 3 — Return transaction details
    return {
      success:     true,
      txHash:      tx.hash,
      blockNumber: receipt.blockNumber,
      gasUsed:     receipt.gasUsed.toString(),
      network:     process.env.NETWORK_NAME || "Ethereum Mainnet",
    };

  } catch (error) {

    // Handle insufficient funds
    if (error.code === "INSUFFICIENT_FUNDS") {
      throw new Error("blockchain: Insufficient funds to pay gas fees.");
    }

    // Handle nonce errors
    if (error.code === "NONCE_EXPIRED") {
      throw new Error("blockchain: Transaction nonce expired. Please retry.");
    }

    // Handle network errors
    if (error.code === "NETWORK_ERROR") {
      throw new Error("blockchain: Network error. Check your RPC URL.");
    }

    console.error("[BLOCKCHAIN] Store error:", error.message);
    throw new Error(`blockchain: Failed to store on chain: ${error.message}`);
  }
};

// ==============================
// storeOnBlockchain.lookup()
// Check if image hash already
// exists on blockchain
// ==============================

storeOnBlockchain.lookup = async (imageHash) => {
  try {

    console.log(`[BLOCKCHAIN] Looking up hash: ${imageHash}`);

    // Call read function on contract
    const result = await contract.getVerification(imageHash);

    // If no record found
    if (!result || result.imageHash === "") {
      return { found: false, data: null };
    }

    // Return found record
    return {
      found: true,
      data: {
        imageHash:   result.imageHash,
        score:       result.score.toString(),
        certified:   result.certified,
        fileName:    result.fileName,
        timestamp:   result.timestamp.toString(),
        blockNumber: result.blockNumber.toString(),
      },
    };

  } catch (error) {
    console.error("[BLOCKCHAIN] Lookup error:", error.message);
    throw new Error(`blockchain: Lookup failed: ${error.message}`);
  }
};

// ==============================
// getVerificationHistory()
// Fetch all past verification
// records from blockchain
// ==============================

export const getVerificationHistory = async ({ skip = 0, limit = 10, search = "" }) => {
  try {

    console.log("[BLOCKCHAIN] Fetching history...");

    // Call contract to get all records
    const records = await contract.getAllVerifications();

    // Convert blockchain data to readable format
    let list = records.map((r) => ({
      id:          r.id.toString(),
      imageHash:   r.imageHash,
      score:       r.score.toString(),
      certified:   r.certified,
      fileName:    r.fileName,
      timestamp:   new Date(r.timestamp.toNumber() * 1000).toISOString(),
      blockNumber: r.blockNumber.toString(),
    }));

    // Apply search filter if provided
    if (search) {
      list = list.filter(
        (r) =>
          r.fileName.toLowerCase().includes(search.toLowerCase()) ||
          r.imageHash.toLowerCase().includes(search.toLowerCase())
      );
    }

    // Total before pagination
    const total = list.length;

    // Apply pagination
    list = list.slice(skip, skip + limit);

    return { list, total };

  } catch (error) {
    console.error("[BLOCKCHAIN] History error:", error.message);
    throw new Error(`blockchain: Failed to fetch history: ${error.message}`);
  }
};

// ==============================
// getVerificationById()
// Fetch single verification
// record by its ID
// ==============================

export const getVerificationById = async (id) => {
  try {

    console.log(`[BLOCKCHAIN] Fetching record by ID: ${id}`);

    const record = await contract.getVerificationById(id);

    if (!record || record.imageHash === "") {
      return null;
    }

    return {
      id:          record.id.toString(),
      imageHash:   record.imageHash,
      score:       record.score.toString(),
      certified:   record.certified,
      fileName:    record.fileName,
      timestamp:   new Date(record.timestamp.toNumber() * 1000).toISOString(),
      blockNumber: record.blockNumber.toString(),
      txHash:      record.txHash,
      network:     process.env.NETWORK_NAME || "Ethereum Mainnet",
    };

  } catch (error) {
    console.error("[BLOCKCHAIN] Fetch by ID error:", error.message);
    throw new Error(`blockchain: Failed to fetch record: ${error.message}`);
  }
};
```

---

### What each part does

``````
blockchainService.js
│
├── setup
│   ├── loads ABI from contracts/artifacts
│   ├── connects to Ethereum via RPC URL
│   ├── creates wallet signer
│   └── creates contract instance
│
├── storeOnBlockchain()
│   ├── Step 1 → calls contract.storeVerification()
│   ├── Step 2 → waits for transaction to be mined
│   └── Step 3 → returns txHash + blockNumber
│
├── storeOnBlockchain.lookup()
│   ├── calls contract.getVerification()
│   └── returns found / not found
│
├── getVerificationHistory()
│   ├── fetches all records from contract
│   ├── applies search filter
│   └── applies pagination
│
└── getVerificationById()
    ├── fetches single record by ID
    └── returns formatted record
```